name: font_preview
description: A package to inspect, compare and preview fonts that are being used in Flutter apps
version: 0.1.4
# publish_to: https://pub.dev/packages/font_preivew
homepage: https://github.com/easazade/font_preivew

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: fallback_font
      fonts: 
        - asset: lib/src/assets/fallback_font/BungeeShade-Regular.ttf

