name: font_preview
description: A package to inspect, compare and preview fonts that are being used in Flutter apps
version: 0.0.1
homepage: 

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: fallback_font
      fonts: 
        - asset: lib/src/assets/fallback_font/RubikStorm-Regular.ttf

